version: '3.8'
services:
  nest_server:
    container_name: resuelve_prueba_zero_nest_server
    build:
      context: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - 3000:3000
    depends_on:
      - postgres_database
      - redis_cache
  postgres_database:
    container_name: resuelve_prueba_zero_postgres_database
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis_cache:
    container_name: resuelve_prueba_zero_redis_cache
    image: redis:7-alpine
    restart: always
    expose:
      - 6379
volumes:
  postgres-data:
