# Base image
FROM node:21-alpine3.17

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Start the server using the production build
CMD [ "npm", "run", "start:dev" ]